version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db  # Use the service name here
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: admin
      DB_PASSWORD: P@ssw0rd!MySQL
      APP_ENV: local  # Add this line


  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: P@ssw0rd!MySQL
      MYSQL_USER: admin
      MYSQL_PASSWORD: P@ssw0rd!MySQL
